# Generated by Django 3.2.4 on 2021-07-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pole', models.CharField(choices=[('Technique.Support', 'Technique.Support'), ('Technique.Prod', 'Technique.Prod'), ('Technique.Dev', 'Technique.Dev'), ('Comptabilite', 'Comptabilite'), ('Garage', 'Garage'), ('Legal Team', 'Legal Team'), ('Operation', 'Operation'), ('Marketing', 'Marketing'), ('Ressources Humaines', 'Ressources Humaines'), ('Relation Client', 'Relation Client'), ('Terrain', 'Terrain')], max_length=100, null=True)),
                ('gmail', models.BooleanField(default=False)),
                ('slack', models.BooleanField(default=False)),
                ('freshdesk', models.BooleanField(default=False)),
                ('jira', models.BooleanField(default=False)),
                ('git', models.BooleanField(default=False)),
                ('maas360', models.BooleanField(default=False)),
                ('azure_ad', models.BooleanField(default=False)),
                ('orchestra', models.BooleanField(default=False)),
                ('office365', models.BooleanField(default=False)),
                ('tempo', models.BooleanField(default=False)),
                ('adminv3', models.BooleanField(default=False)),
                ('code_app', models.BooleanField(default=False)),
                ('cs_app', models.BooleanField(default=False)),
                ('cs_looper', models.BooleanField(default=False)),
                ('live_fleet', models.BooleanField(default=False)),
                ('tableau', models.BooleanField(default=False)),
                ('vpn', models.BooleanField(default=False)),
                ('rancher', models.BooleanField(default=False)),
                ('aws', models.BooleanField(default=False)),
                ('ovh', models.BooleanField(default=False)),
                ('jumio', models.BooleanField(default=False)),
                ('ogone', models.BooleanField(default=False)),
                ('rabbit', models.BooleanField(default=False)),
                ('grafana', models.BooleanField(default=False)),
                ('sentry', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=30, verbose_name='Prenom')),
                ('date', models.DateField()),
                ('pole', models.CharField(choices=[('Technique.Support', 'Technique.Support'), ('Technique.Prod', 'Technique.Prod'), ('Technique.Dev', 'Technique.Dev'), ('Comptabilite', 'Comptabilite'), ('Garage', 'Garage'), ('Legal Team', 'Legal Team'), ('Operation', 'Operation'), ('Marketing', 'Marketing'), ('Ressources Humaines', 'Ressources Humaines'), ('Relation Client', 'Relation Client'), ('Terrain', 'Terrain')], max_length=100)),
                ('ville', models.CharField(choices=[('Paris', 'Paris'), ('Nice', 'Nice'), ('Milan', 'Milan'), ('Barcelone', 'Barcelone')], max_length=100, null=True)),
                ('pole_id', models.ManyToManyField(to='matricesheet.App')),
            ],
        ),
    ]
